FROM python:3.12-slim

# Install system dependencies
RUN apt-get update && apt-get install -y gcc curl build-essential

# Install pipenv globally
RUN pip install pipenv

WORKDIR /app

# Copy Pipfile and Pipfile.lock early to leverage caching
COPY Pipfile* ./

# Install Python dependencies
RUN pipenv install --deploy --ignore-pipfile

# Copy the rest of your application code
COPY . .

# At runtime, first apply Alembic migrations, then start the app
CMD ["sh", "-c", "pipenv run alembic upgrade head && pipenv run gunicorn -b :$PORT app.main:app"]
